### ISSUE TITLE
Use gh-pages branch

### ISSUE THREAD

**Issue by DonKarlssonSan** [bit101/quicksettings#10]
This is more of a question really.
In the readme I noticed that there are several links to http://htmlpreview.github.io. Like the demos for example.

Why not keep everything in the gh-pages branch and then everything will be served as proper web pages?

http://htmlpreview.github.io/?https://github.com/bit101/quicksettings/blob/master/demos/master_demo.html
->
http://bit101.github.io/quicksettings/demos/master_demo.html

**Comment by bit101** [comment]
Thanks. I'll look into it. I'm not super familiar with gh-pages, but that sounds like a great solution.

**Comment by DonKarlssonSan** [comment]
Have a look at my Buddhabrot renderer, it uses gh-pages:
https://github.com/DonKarlssonSan/BuddhabrotJs
As long as you are ok with gh-pages being the default branch, GitHub takes care of the rest.

**Comment by jackrugile** [comment]
Just a quick note for the sake of organization and preference: You have some more options for how to set this up now. As of August 17, 2016, you can assign GitHub to serve up any branch, or any branch with a `/docs` directory: https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by bit101** [comment]
So much to learn.

**Comment by johanberonius** [comment]
The is also https://rawgit.com/ to serve pages with with proper Content-Type headers.
https://cdn.rawgit.com/bit101/quicksettings/master/doc/module-QuickSettings.html

**Comment by bit101** [comment]
The docs directory thing looks just like what I need. Started to flesh that out in the "next" branch.

**Comment by bit101** [comment]
demos and  api docs are now in docs/ Good move. I'll flesh it out more later, but thanks for all the suggestions.
