### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by johanberonius** [bit101/quicksettings#12]
Is there a button to reset all values to their defaults? I could not find any.
Otherwise, that might be a feature suggestion.

Anyway, thanks for quicksettings! Used them for the first time today and it was very easy.

**Comment by bit101** [comment]
Not a bad idea. I'm making some changes now and I'll look into that.

**Comment by bit101** [comment]
I looked into this and started making a change, but realized it can be done with a couple of lines of code using the get/set values as json, like so:

	var settings = QuickSettings.create(20, 20, "Settings")
		.addRange("range", 0, 100, 50, 1)
		.addText("text", "hello world")
		.addColor("color", "#ff0000")
		.addBoolean("boolean", true)
		.addButton("reset", function() {
			settings.setValuesFromJSON(defaultValues);
		});

	var defaultValues = settings.getValuesAsJSON();

Note: the setValuesFromJSON function is in the "next" branch only for now, but will be coming out in v3 shortly.
