### ISSUE TITLE
current quicksettings version is incorrect

### ISSUE THREAD

**Issue by MatthijsKamstra** [bit101/quicksettings#15]
<https://cdn.jsdelivr.net/quicksettings/3.0/quicksettings.min.js>

search for `version`

![screen shot 2016-12-13 at 17 09 40](https://cloud.githubusercontent.com/assets/907219/21147965/01c865de-c157-11e6-880e-9b6f0495a022.png)

it still version 2.1

**Comment by bit101** [comment]
fixed. not that it was used for anything.

**Comment by MatthijsKamstra** [comment]
sure, it is kinda stupid I found out. I was updating old `<3` code 
Great work btw: thx

**Comment by bit101** [comment]
All good. Keep any feedback coming. I appreciate it.
