### ISSUE TITLE
Enhancement: allow different value and label for dropdown menus

### ISSUE THREAD

**Issue by cotejp** [bit101/quicksettings#17]
It would be very convenient if we could pass an array of objects as the second parameter to the `addDropDown()` function. This would allow specifying labels that are different from the actual value. Since `getValue()` already returns an object for dropdowns, this would remain consistent.

A good example of that is creating a dropdown menu for currently connected webcams. The usable value (the device id) is a long chain of gibberish that gives no information about the device itself:

```javascript
settings.addDropDown(
  "Webcam", 
  [
    {
      value: "3c3a9021070396c22e983ceac201a06da9531b63bbeabb6119789b0d1f93ec88", 
      label:  "FaceTime HD Webcam (builtin) (05ac:8510)"
    },
    {
      value: "af9d079a3f4b73343c7c0fa580fdfd6f744d6615f6e6bc41a2fc307c03f6d873", 
      label:  "HD Pro Webcam C920 (046d:082d)"
    }
  ]
  ,
); 
```

**Comment by bit101** [comment]
That sounds logical. Let me work on it.

**Comment by bit101** [comment]
done
