### ISSUE TITLE
hide html control generates an error

### ISSUE THREAD

**Issue by CarbonMan** [bit101/quicksettings#27]
Nice utility.
I have a variety of controls loaded into a panel, but if I attempt to hide a HTML control I get
Uncaught TypeError: Cannot read property 'style' of undefined

You can get this to happen on the HTMLdemo ( http://bit101.github.io/quicksettings/demos/htmldemo.html ) by executing
settings.hideControl("info")
at the end of the window.onload function.

Thanks.

**Comment by MarcelKlammer** [comment]
Yes, stumbles upon this, too. Please add container: container to the object in addHTML.

**Comment by CarbonMan** [comment]
Sorry, I don't follow.
I have ;
panel.addHTML("IP address", "<div><b>text</b></div>");
what should I add?

**Comment by MarcelKlammer** [comment]
Sorry, I meant Keith. But you can fix it in your local quicksettings.js fill. Look for addHTML. In that function the object this._controls[title] the entry container: container is missing.

**Comment by bit101** [comment]
Fixed this.
