### ISSUE TITLE
[question] bindValue

### ISSUE THREAD

**Issue by SeregPie** [bit101/quicksettings#37]
A short question. I was looking for an alternative for dat.GUI. Your project looks great. But your API is kind of strange.

For example `bindBoolean`

```js

bindBoolean(title, value, object) {
  return this.addBoolean(title, value, value => {
    object[title] = value;
  });
}

```
Why is it `this.addBoolean(title, value, ...` and not just `this.addBoolean(title, object[title], ...`? The `value` attribute would be unnecessary.

**Comment by bit101** [comment]
yeah, that would probably work. unless object[title] was not set yet. it means . you'd have to fully populate object first before setting up the panel.
