### ISSUE TITLE
Generic addInput()

### ISSUE THREAD

**Issue by Distjubo** [bit101/quicksettings#5]
I think a generic addInput function would be a good way to

1. clean up all the code thats already there (you could pass an object containing all the attributes the new element should contain)

2. provide a way of adding unsupported input-elements

**Comment by bit101** [comment]
Thanks. I'll look into this. Sounds like a good idea.

**Comment by bit101** [comment]
I looked into this some more and not sure I see a huge benefit. There are several types of input controls in use, but each is created and handled very differently. I understand the part about passing an object with properties, but there are differences beyond that. I'm not sure that it would clean up all that much in the long run.

As for #2, are there unsupported input elements that you would like to see added?

**Comment by Distjubo** [comment]
The only input element I have manually added in the past was a good old number input. I have also added a canvas element but I guess thats barely an input

**Comment by bit101** [comment]
The addElement and addHTML methods make it very extensible. I just added addDate, addTime, addPassword. I'll have to look into number inputs.
