### ISSUE TITLE
Feature Request: File Chooser.

### ISSUE THREAD

**Issue by MarcelKlammer** [bit101/quicksettings#7]
Hi Keith,

would love to have a simple solutions for choosing a file.

Cheers
Marcel

**Comment by bit101** [comment]
Good idea.

**Comment by bit101** [comment]
Just put one together and did a push. Needs more cross browser/platform testing and documentation. Then I'll make a new release. But if you grab the latest from github, you can try it out.

**Comment by bit101** [comment]
So yeah, that's fully in, tested, documented, released. Hope it's useful.
